### PR TITLE
new logo and favicon

### PR DESCRIPTION
**Pull request by ajs124**
Converted with https://www.favicon-generator.org/

The logo was shrunk to 698x512 px. Do you maybe have a svg we could use instead?

I tested this locally, the website still shows the old logo.

### CODE REVIEW

**Comment by egekorkan** [comment]
I have PDF but can get an SVG as well. PDF is attached here
[favicon.pdf](https://github.com/tum-esi/wot-marketplace/files/4708070/favicon.pdf)

**Comment by egekorkan** [comment]
Why still the old logo?

**Comment by ajs124** [comment]
I meant the live website. This replaces the logo, but it's not live on wotify.org yet, because nobody deployed it.

**Comment by egekorkan** [comment]
Could you deploy it? I have redirected it already

**Comment by ajs124** [comment]
This branch is deployed now.

**Pull request merged**
